### ISSUE TITLE
Error running in python enviromment with parameter tidy

### ISSUE THREAD

**Issue by zdenkor** [sapristi/mail_juicer#4]
When I create python enviromment and run mmuxer tidy --folder FOLDER I get an error "TypeError: BaseMailBox._fetch_in_bulk() takes 4 positional arguments but 5 were given"

**Comment by sapristi** [comment]
Hello, thanks for the feedback. Indeed there was something broken (the imap-tools library had a new version). I have published version 0.6.2 which should solve the issue !  (you will have to recreate the python env, so as to make sure the right version if imap-tools is used).

Please let me know how it goes !

**Comment by zdenkor** [comment]
Hello, looks like that the problem is in combination with python 3.12.0. When I used older version 3.11.4, there was no error. I did not try actual version of python.

**Comment by sapristi** [comment]
Ok, that's strange. I have published yet another version ( **0.6.3** ) that's compatible with newer imap-tools. 

I just added tests for python 3.12, there doesn't seem to be any particular issue.

Can you post the full install logs, with each library version that is used ?

**Comment by sapristi** [comment]
Closing since no new report
